USE DATABASE NYC_TAXI;
USE SCHEMA YELLOW_TAXI;

-- PLOT BOROUGHS AND SUM OF SALES / FARES

SELECT BOROUGH, 
    SUM(TOTAL_AMOUNT) AS SUM_OF_FARES, 
    COUNT(*) AS COUNT_OF_TRIPS
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_ZONES B
    ON A.PICKUP_ZONE = B.LOCATIONID
GROUP BY BOROUGH;

-- AVG FARE AND BY DAY OF WEEK

SELECT DAYOFWEEK(PICKUP_TIME) AS ORD, 
        DAYNAME(PICKUP_TIME) AS DAY_OF_WEEK,  
        ROUND(AVG(TOTAL_AMOUNT), 2) AS AVG_FARE_AMOUNT
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_RATES B
    ON A.RATECODEID = B.RATE_CODE
GROUP BY ORD, DAY_OF_WEEK
ORDER BY ORD;

-- GET VENDOR SUM, TIPS AND TIPS PERCENTAGE

SELECT VENDOR_DESCRIPTION, 
        SUM(TOTAL_AMOUNT) SUM_OF_FARES, 
        SUM(TIP_AMOUNT) TOTAL_TIPS, 
        ROUND(SUM(TIP_AMOUNT) / SUM(TOTAL_AMOUNT) *100, 2) AS TIP_PERCENTAGE
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_VENDORS B
    ON A.VENDORID = B.VENDOR_CODE
GROUP BY VENDOR_DESCRIPTION;
