-- TRIPS BY MONTH --
SELECT 
MONTH(PICKUP_TIME) DATE,  
    COUNT(*) AS COUNT_OF_TRIPS
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_ZONES B
    ON A.PICKUP_ZONE = B.LOCATIONID
GROUP BY DATE
 ORDER BY DATE DESC;

-- PLOT BOROUGHS TRIPS --
SELECT BOROUGH,  
    COUNT(*) AS COUNT_OF_TRIPS
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_ZONES B
    ON A.PICKUP_ZONE = B.LOCATIONID
GROUP BY BOROUGH;

-- AVG FARE AND BY DAY OF WEEK --
SELECT  HOUR(PICKUP_TIME) TIME,
        DAYOFWEEK(PICKUP_TIME) AS ORD, 
        DAYNAME(PICKUP_TIME) AS DAY_OF_WEEK,  
        ROUND(AVG(TOTAL_AMOUNT), 2) AS AVG_FARE_AMOUNT
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_RATES B
    ON A.RATECODEID = B.RATE_CODE
GROUP BY ORD, TIME, DAY_OF_WEEK
ORDER BY ORD;

-- GET VENDOR SUM, TIPS AND TIPS PERCENTAGE
SELECT 
    B.VENDOR_DESCRIPTION,
    fee_type,
    SUM(fee_amount) AS total_fee_amount,
    CASE 
        WHEN fee_type = 'TIP' THEN 
            ROUND(SUM(fee_amount) / SUM(total_amount_for_pct) * 100, 2)
    END AS tip_percentage
FROM (
    SELECT 
        VENDORID,
        TOTAL_AMOUNT AS fee_amount,
        TOTAL_AMOUNT AS total_amount_for_pct,
        'FARE' AS fee_type
    FROM FCT_YELLOW_TRIPS

    UNION ALL

    SELECT
        VENDORID,
        TIP_AMOUNT AS fee_amount,
        TOTAL_AMOUNT AS total_amount_for_pct,
        'TIP' AS fee_type
    FROM FCT_YELLOW_TRIPS
) t
LEFT JOIN DIM_TBL_VENDORS B
    ON t.VENDORID = B.VENDOR_CODE
GROUP BY B.VENDOR_DESCRIPTION, fee_type;





