-- PLOT BOROUGHS AND SUM OF SALES / FARES

SELECT BOROUGH, SUM(TOTAL_AMOUNT) AS SUM_OF_FARES, COUNT(TRIP_ID)
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_ZONES B
    ON A.PICKUP_ZONE = B.LOCATIONID
GROUP BY BOROUGH
;

-- AVG FARE AND PASSENGERS BY DAY OF WEEK

SELECT DAYOFWEEK(PICKUP_TIME) ORD, DAYNAME(PICKUP_TIME) DAY_OF_WEEK, ROUND(AVG(PASSENGER_COUNT)) AVG_PASSENGERS, AVG(TOTAL_AMOUNT) AVG_FARE_AMOUNT
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_RATES B
    ON A.RATECODEID = B.RATE_CODE
GROUP BY ORD, DAY_OF_WEEK
ORDER BY ORD
;

-- GET VENDOR SUM, TIPS AND TIPS PERCENTAGE

SELECT VENDOR_DESCRIPTION, SUM(TOTAL_AMOUNT) SUM_OF_FARES, SUM(TIP_AMOUNT) TOTAL_TIPS, SUM(TIP_AMOUNT) / SUM(TOTAL_AMOUNT) *100 AS TIP_PERCENTAGE
FROM FCT_YELLOW_TRIPS A
    LEFT JOIN DIM_TBL_VENDORS B
    ON A.VENDORID = B.VENDOR_CODE
GROUP BY VENDOR_DESCRIPTION